### ISSUE TITLE
newest miio version 0.15.6

### ISSUE THREAD

**Issue by cflurin** [aformusatii/node-red-contrib-xiaomi-miio#2]
Wy are you using miio version 0.13.0?

**Comment by Gromina** [comment]
@aformusatii are you working on version bump? If no I could help and make PR for that

**Comment by cflurin** [comment]
Never mind, I've published a new package:
https://github.com/cflurin/xiaomi-mqtt

**Comment by aformusatii** [comment]
Done as well, sorry for the delay.
