### ISSUE TITLE
No items on miio device in Node-Red

### ISSUE THREAD

**Issue by rolfz** [aformusatii/node-red-contrib-xiaomi-miio#5]
I have configured miio from the Manage Palette. The nodes appear as expected in the left hand menu on Node-Red, but I see no devices for example inside the cube node. I have node-red installed from openhabian. Does anyone know how to initialize miio ?

**Comment by aformusatii** [comment]
Hi rolfz, please consider updating the library to latest version 0.0.6 it might help, if not then see these steps:
https://github.com/aholstenson/miio/blob/master/docs/management.md

**Comment by aformusatii** [comment]
Looks similar reason to https://github.com/aformusatii/node-red-contrib-xiaomi-miio/issues/3 closing.
