### ISSUE TITLE
Cannot start node-red when add this node

### ISSUE THREAD

**Issue by rxrw** [aformusatii/node-red-contrib-xiaomi-miio#6]
When I tried to install this node to my node-red, I can't start it with following errors:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/9566402/51697497-e85f4980-2042-11e9-8b0f-cf11158f60b7.png">
It seems `miio` found some devices and got undefined property so that it's information cannot parse json. When I remove this node It's ok to run. But I need this~😊

**Comment by aformusatii** [comment]
If this is still an issue, could you please provide:
miio version (npm view miio version)
nodered version

I suspect you are using old version of miio, you should be using >= 0.15.6.

**Comment by rxrw** [comment]
with time goes by..
